server:
  port: 8888
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@jmento.iptime.org:8922:xe
    username: BRINGBRING
    password: BRINGBRING
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      location: /tmp
#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-id: oWq7iXzHYNRYo_as3iSc
#            client-secret: 9GSiGzyMtY
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            client-name: Naver
#            redirect-uri: http://localhost:8888/social/naverCode
#            scope:
#            - id
#            - name
#            - profile_image
#            - mobile
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 요청 uri
#            token-uri: https://nid.naver.com/oauth2.0/token # 토큰을 발급받기 위한 uri
#            user-info-uri: https://openapi.naver.com/v1/nid/me # 유저 정보를 받아오기 위한 uri
#            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌

mybatis:
  configuration:
    jdbc-type-for-null: NULL    
  

    