server:
  port: 8888
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@jmento.iptime.org:8922:xe
    username: BRINGBRING
    password: BRINGBRING
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      location: /tmp
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
mybatis:
  configuration:
    jdbc-type-for-null: NULL    
  

    